# Generated by Django 2.2 on 2020-06-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200621_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Session', verbose_name='جلسه ی این درس'),
        ),
    ]
