# Generated by Django 2.2 on 2020-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_session_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='username',
        ),
        migrations.AddField(
            model_name='course',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
