# Generated by Django 2.2 on 2020-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200710_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('c', 'در حال برگزاری'), ('f', 'تکمیل شده')], max_length=10, null=True, verbose_name='وضعیت دوره'),
        ),
    ]
