# Generated by Django 2.2 on 2020-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('درحال برگزاری', 'در حال برگزاری'), ('تکمیل شده', 'تکمیل شده')], max_length=10, null=True, verbose_name='وضعیت دوره'),
        ),
    ]
