# Generated by Django 2.2 on 2020-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200802_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('در حال برگزاری', 'درحال برگزاری'), ('تکمیل شده', 'تکمیل شده')], default='در حال برگزاری', max_length=15, null=True, verbose_name='وضعیت دوره'),
        ),
    ]
